language: java

jdk:
  - oraclejdk11

before_cache:
  - rm -rf $HOME/.m2/repository/iuh/fit/maikiencuong/test-circleci/maven-metadata-local.xml
  - rm -rf $HOME/.m2/repository/iuh/fit/maikiencuong/test-circleci/*/*.jar\n

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - travis-ci

before_install:
  - chmod +x mvnw

script:
  - java --version
  - mvn --version
  - mvn clean package -Dmaven.test.skip
  - pwd
  - whoami
  - ls
  - echo current user ${CURRENT_USER}