name: my-workflow
on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - feature/github-actions
jobs:
  docker-build-and-push-job:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: list all file
        run: ls && ls ./target
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - name: show info
        run: pwd && ls && whoami


