name: my-workflow
on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - feature/github-actions
jobs:
  docker-build-and-push-job:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip --file pom.xml

      - name: list all file
        run: ls && ls ./target
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - name: show info
        run: pwd && ls && whoami
  deploy:
    runs-on: ubuntu-18.04
    needs:
      - docker-build-and-push-job
      - test-job
    steps:
      - name: show info
        run: pwd && ls && whoami


